#!/bin/sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

SB_BIN_DIR="$ROOT_DIR/.bin"
SB_BIN="$SB_BIN_DIR/supabase"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

install_supabase_cli() {
  if [ -x "$SB_BIN" ]; then
    return 0
  fi

  need_cmd curl
  need_cmd tar

  mkdir -p "$SB_BIN_DIR"

  OS=$(uname -s | tr '[:upper:]' '[:lower:]')
  ARCH=$(uname -m)

  if [ "$OS" != "linux" ]; then
    echo "Auto-install only supports Linux right now. Install Supabase CLI manually." >&2
    exit 1
  fi

  case "$ARCH" in
    x86_64|amd64) SB_TGZ="supabase_linux_amd64.tar.gz" ;;
    aarch64|arm64) SB_TGZ="supabase_linux_arm64.tar.gz" ;;
    *)
      echo "Unsupported arch for auto-install: $ARCH" >&2
      exit 1
      ;;
  esac

  URL="https://github.com/supabase/cli/releases/latest/download/$SB_TGZ"
  TMP="$SB_BIN_DIR/.supabase.tmp.tgz"

  echo "[dev] downloading Supabase CLI: $URL"
  curl -fsSL "$URL" -o "$TMP"

  echo "[dev] extracting Supabase CLI"
  tar -xzf "$TMP" -C "$SB_BIN_DIR"
  rm -f "$TMP"

  if [ ! -x "$SB_BIN" ]; then
    chmod +x "$SB_BIN" || true
  fi

  if [ ! -x "$SB_BIN" ]; then
    echo "Supabase CLI install failed: $SB_BIN not executable" >&2
    exit 1
  fi
}

supabase_env_value() {
  # usage: supabase_env_value KEY
  KEY="$1"
  "$SB_BIN" status -o env | awk -F= -v k="$KEY" '$1==k { sub(/^[^=]*=/, ""); print; exit }'
}

write_dotenv() {
  ENV_FILE="$ROOT_DIR/.env"

  API_URL=$(supabase_env_value API_URL)
  ANON_KEY=$(supabase_env_value ANON_KEY)
  SERVICE_ROLE_KEY=$(supabase_env_value SERVICE_ROLE_KEY)
  JWT_SECRET=$(supabase_env_value JWT_SECRET)

  if [ -z "$API_URL" ] || [ -z "$ANON_KEY" ] || [ -z "$SERVICE_ROLE_KEY" ]; then
    echo "Failed to read Supabase keys from 'supabase status'. Is Supabase running?" >&2
    exit 1
  fi

  echo "[dev] writing $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Generated by ./dev.sh

# Local Postgres for Prisma
POSTGRES_USER=pace42
POSTGRES_PASSWORD=pace42
POSTGRES_DB=pace42

# Backend
CORS_ORIGIN=http://localhost:5173

# Supabase (local)
SUPABASE_URL=$API_URL
SUPABASE_ANON_KEY=$ANON_KEY
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY
SUPABASE_JWT_SECRET=$JWT_SECRET

# Frontend
VITE_BACKEND_URL=http://localhost:3004
VITE_SUPABASE_URL=$API_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
EOF
}

cmd_up() {
  need_cmd docker
  need_cmd awk

  install_supabase_cli

  echo "[dev] starting Supabase (local)"
  "$SB_BIN" start

  write_dotenv

  echo "[dev] starting app (frontend + backend + db)"
  docker compose up --build
}

cmd_down() {
  need_cmd docker
  install_supabase_cli

  echo "[dev] stopping app"
  # docker compose needs supabase env vars to interpolate; provide dummies if .env is missing
  if [ -f "$ROOT_DIR/.env" ]; then
    docker compose down
  else
    SUPABASE_URL=http://dummy SUPABASE_ANON_KEY=dummy SUPABASE_SERVICE_ROLE_KEY=dummy VITE_SUPABASE_URL=http://dummy VITE_SUPABASE_ANON_KEY=dummy docker compose down
  fi

  echo "[dev] stopping Supabase (local)"
  "$SB_BIN" stop --no-backup || true
}

case "${1:-}" in
  up) cmd_up ;;
  down) cmd_down ;;
  *)
    echo "Usage: ./dev.sh up|down" >&2
    exit 1
    ;;
esac
